### ISSUE TITLE
Couple of Issues on First Try

### ISSUE THREAD

**Issue by theAkito** [osxzxso/directory-visualizer#1]
Greetings 👋🏻

Thank you for this extension.

I have noticed a couple of issues with this, after using it for a minute.

* It's not clear, that you have to press `Regenerate`, when Directories are de-selected in the `Select Directories` view.
* It's really hard to find the `Regenerate` button, because you have to scroll really far down, since every `.git` file is included & shown by default. You have to scroll a lot, but not too much, because else you see the visualisation, instead of the `Select Directories` section. The `Regenerate` button should be on top.
* The `Select Directories` section should be left/right next to the visualisation, so you can compare easily.
* Ideally, the `Regenerate` button should not be necessary & the view should automatically refresh on change.
* Directories like `.git` & maybe even directories with tons of spammy files on a single level should be de-selected by default. Most of the time, you don't wanna see those in your tree, I would expect.
* In a later stage of development, it would be nice to see the possibility of writing rules, filters, etc.
* The naming in the Command Palette should have the word "Directory" in it, rather than just "Generate Tree Map", because it's easiest to find, this way.

Otherwise, good start. 😄

**Comment by osxzxso** [comment]
Hello there and thank you for reaching out!

- Any suggestions on how to make it more clear? There were two options that I considered: Option 1 - Have the tree map update as you are checking and unchecking directories, but that may become inefficient for large workspaces (constantly generating the tree map each time a directory is checked or unchecked), but I will look into Option 1 again, and test it for a longer period of time to see how it feels, Option 2 - Do your checking and unchecking and then click Regenerate when you are ready (which is the option I went with).
- I debated between placing the button at the top of the checkbox tree map or the bottom. Both locations pose issues. If you're checking and unchecking things near the bottom, then having the button there is convenient. If you're checking and unchecking things near the top, then having the button there is convenient.  Perhaps in a new version, I will add a floating button that remains present in a corner at all times or some sort of placement that is even more efficient than the top or bottom of the checkbox tree (as both of those placements have their drawbacks, especially with large workspaces).
- The problem with having them left/right is screen size. If viewed on a monitor, it is fine to do so. If viewed on a monitor snapped to 50% width of display, it's not so fine. Also, on a smaller laptop screen it is not ideal either to have them left/right. Some directories are heavily nested and then you are just migrating to horizontal versus vertical scrolling. Open up a heavily nested workspace and you'll see how left and right could become ugly. But I know what you mean about wanting to see them side by side for comparisons.
- I addressed this concept in the first bullet.
- While developing the extension, I hard-coded the exclusion of the `.git` and `node_modules` directories for the exact reason you stated, they are rarely needed in the visualization (tree map). However, the Select Exclusions tab is where you should set those exclusions. Some people may want those folders included, most probably won't, but the idea is that they do have the ability to set them (or any other directory, file, or file type) as exclusions. Also, you can see in the README.md file that a later version will have persistence, and the ability to create global exclusions (which will apply to all workspaces) and workspace specific exclusions (which will apply to specific workspaces). Effectively allowing you to exclude `.git` or `node_modules` globally (which is essentially what you are requesting), but at least you get to make the choice to set that versus me forcing it.
- Great Ideas! Rules, filters, and many other ways to customize the tree map will be arriving in future releases. Some details are in the README.md file.
- You are right on. I will change that. Possibly "Directory Visualizer: Generate Tree Map" or just the extension name "Directory Visualizer" or "Open Directory Visualizer", something like that?

**Comment by theAkito** [comment]
> * Any suggestions on how to make it more clear? There were two options that I considered: Option 1 - Have the tree map update as you are checking and unchecking directories, but that may become inefficient for large workspaces (constantly generating the tree map each time a directory is checked or unchecked), but I will look into Option 1 again, and test it for a longer period of time to see how it feels, Option 2 - Do your checking and unchecking and then click Regenerate when you are ready (which is the option I went with).

The way I am used to this situation, is that whatever app I use, like for example, Visual Studio Code, adds a star `*` to the file's name in the top tab row. Then, in case of such buttons, the button to be pressed, usually some kind of "save" button, in this case this is the `Regenerate` button, it should change colour, for example turn to red, once changes are immediately detected. If no changes are present, it should be greyish or at least of no alarming colour.

This obviously implies, the `Regenerate` button is always easily visible, ideally the entire time during editing or at least it has to be extremely clear from the get go, if the button becomes non-visible at some point.



> * I debated between placing the button at the top of the checkbox tree map or the bottom. Both locations pose issues. If you're checking and unchecking things near the bottom, then having the button there is convenient. If you're checking and unchecking things near the top, then having the button there is convenient.  Perhaps in a new version, I will add a floating button that remains present in a corner at all times or some sort of placement that is even more efficient than the top or bottom of the checkbox tree (as both of those placements have their drawbacks, especially with large workspaces).

Indeed.



> * The problem with having them left/right is screen size. If viewed on a monitor, it is fine to do so. If viewed on a monitor snapped to 50% width of display, it's not so fine. Also, on a smaller laptop screen it is not ideal either to have them left/right. Some directories are heavily nested and then you are just migrating to horizontal versus vertical scrolling. Open up a heavily nested workspace and you'll see how left and right could become ugly. But I know what you mean about wanting to see them side by side for comparisons.

If it's truly this difficult, I would just add another button, which let's the user decide on which view to choose. This way, we fix 99% of such issues, I guess.



> * While developing the extension, I hard-coded the exclusion of the `.git` and `node_modules` directories for the exact reason you stated, they are rarely needed in the visualization (tree map). However, the Select Exclusions tab is where you should set those exclusions. Some people may want those folders included, most probably won't, but the idea is that they do have the ability to set them (or any other directory, file, or file type) as exclusions. Also, you can see in the README.md file that a later version will have persistence, and the ability to create global exclusions (which will apply to all workspaces) and workspace specific exclusions (which will apply to specific workspaces). Effectively allowing you to exclude `.git` or `node_modules` globally (which is essentially what you are requesting), but at least you get to make the choice to set that versus me forcing it.

That's fine, but then you have to telegraph that to the user. I saw some filter stuff, but when I tried it out the first time, I didn't think to what felt like "dive deep" to get this working. It should be "easy" from the beginning or it should be very obvious, that a simple filter is needed or maybe some filter preset with according one-click buttons.
The least there is needed regarding this, is that the user needs to *know* how to quickly make the view more reasonable. At least some pop-up telling the user, what should usually be done, is necessary for starters.



> * You are right on. I will change that. Possibly "Directory Visualizer: Generate Tree Map" or just the extension name "Directory Visualizer" or "Open Directory Visualizer", something like that?

Is it possible to have invisible tags? Like, if you are searching for a tag word, but it's not actually in the title?
If yes, I would add tag words like folder, directory, folders, directories, map, tree, visualise, visualize, visualizer, visualiser.

If no, it should be at least "Open Directory Visualizer" or uglier, but safer would even be "Open Directory/Folder Visualizer", if you truly want to make the search as easy for everyone, as possible.
"Visualize Directories/Folders" or something would be possible, too. However, this is just optimisation, in case there are no hidden tags available.

**Comment by osxzxso** [comment]
Just wanted to thank you again for using the extension and reaching out with some great suggestions. Will consider them in future updates.
